all:
  children:

    swarm_manager:
      hosts:
        dev.diesel.net:

  vars:

    hosts: 
      - home.dev.diesel.net

    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
