all:
  children:

    swarm_manager:
      hosts:
        tools.diesel.net:

  vars:

    hosts: 
      - diesel.net
      - home.diesel.net
    
    ansible_user: automation
    ansible_python_interpreter: /usr/bin/python3
