version: '3.8'
services: 

  dashboard:
    image: b4bz/homer:22.02.2
    environment:
      - INIT_ASSETS=0
    volumes:
      - /etc/localtime:/etc/localtime
      - {{ config_dir }}/assets/:/www/assets:r
     
    networks:
      - {{ traefik_network }}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.{{ repository }}.loadbalancer.server.port=8080
        - traefik.http.routers.{{ repository }}.rule=Host(`{{ hosts | join('`,`') }}`)
        - traefik.http.routers.{{ repository }}.service={{ repository }}
        - traefik.http.routers.{{ repository }}.tls.certresolver=step-ca

networks:
  {{ traefik_network }}:
    external: true
    name: {{ traefik_network }}
