- hosts: handbrake
  roles:
    - common
    - traefik

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - name: 'Copy custom assets into {{ config_dir }}'
      copy:
        src: '{{ playbook_dir }}/../assets/'
        dest: '{{ config_dir }}' 

    - include_role:
        name: docker
        tasks_from: stack_deploy
      vars:
        docker_compose_template: docker-compose.yaml.j2
