- hosts: handbrake
  roles:
    - common
    - traefik

  tasks:

    - include_role:
        name: common
        tasks_from: make_config_dir

    - name: 'Sync custom assets into {{ config_dir }}'
      synchronize:
        mode: push
        dirs: yes
        delete: yes
        src: '{{ playbook_dir }}/../assets/'
        dest: '{{ config_dir }}' 
      become: yes

    - include_role:
        name: docker
        tasks_from: stack_deploy
      vars:
        docker_compose_template: docker-compose.yaml.j2
