- hosts: swarm_manager
  roles:
    - application
    - traefik

  tasks:

    - include_role:
        name: application
        tasks_from: make_config_dir

    - name: Set file permissions on '{{ confi_dir }}'
      file:
        path: '{{ config_dir }}'
        owner: 911
        group: 911
      become: yes

    - name: 'Sync custom assets into {{ config_dir }}'
      synchronize:
        mode: push
        dirs: yes
        delete: yes
        src: '{{ playbook_dir }}/../assets/'
        dest: '{{ config_dir }}' 
      become: yes

    - include_role:
        name: docker
        tasks_from: stack_deploy
      become: yes
