---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: DIESEL.NET
subtitle: Home
logo: "assets/images/kiwi-labs.png"
#icon: "fas fa-skull-crossbones" # Optional icon

header: true # set false if you want to hide it.
footer: |
  <p>
    
    <a href="https://github.com/Diesel-Net/homer">
      Configure on &nbsp;
      <i class="fab fa-github-alt"></i>
    </a>
  </p>

columns: 4 # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level. 

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
# stylesheet:
#   - "assets/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#ffffff"
    highlight-secondary: "#b3dd45" #b8d094 #4285f4
    highlight-hover: "#ffffff"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#ffffff"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.8)
    link: "#000000"
    link-hover: "#b3dd45"
    background-image: ../assets/images/kiwi-labs-light-3.png
  dark:
    highlight-primary: "#2b2b2b" #4a3418 #474826
    highlight-secondary: "#414233" #474826 #2b2b2b
    highlight-hover: "#8cad27"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#ffb100"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.8)
    link: "#ffffff"
    link-hover: "#8cad27"
    background-image: ../assets/images/kiwi-labs-dark.png

# Optional message
#message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: Chuck Norris Says...
  #   content: value
  # refreshInterval: 10000
  # #style: "is-warning"
  # #title: "Optional message!"
  # #icon: "fa fa-exclamation-triangle"
  # content: ''

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:

  - name: Kiwi Labs
    icon: fab fa-github
    url: https://github.com/Diesel-Net

  - name: Wikipedia
    icon: fas fa-book
    url: https://www.wikipedia.org/
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  # - name: Second page!
  #   icon: fas fa-file-alt
  #   url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:

  - name: Core Infrastructure
    icon: fas fa-network-wired
    items:

      - name: Cloudflare
        logo: assets/images/cloudflare.svg
        subtitle: Registrar, DNS, and CDN
        tag: cloudflare
        url: https://dash.cloudflare.com
        target: "_blank" # open in new tab

      - name: Proxmox VE
        logo: assets/images/pve.png
        subtitle: Hyperconverged Infrastructure
        tag: pve
        url: https://pve.diesel.net:8006
        target: "_blank" # open in new tab

      - name: pfSense
        logo: assets/images/pfsense.png
        subtitle: Firewall, Router, DNS, VPN
        tag: pfsense
        url: https://pfsense.diesel.net:8443
        target: "_blank" # open in new tab

      - name: Cisco SG250-08HP
        logo: assets/images/cisco.png
        subtitle: Managed L2/L3 Switch
        tag: switch
        url: https://switch.diesel.net
        target: "_blank" # open in new tab

      - name: TP-Link SG116E
        logo: assets/images/tplink.png
        subtitle: Managed L2 Switch
        tag: switch
        url: https://tplink.switch.diesel.net
        target: "_blank" # open in new tab

      - name: TP-Link EAP650
        logo: assets/images/tplink2.png
        subtitle: Wireless Access Point
        tag: wap
        url: https://wap.diesel.net
        target: "_blank" # open in new tab

      - name: Asus RT-AX88U
        logo: assets/images/merlin.png
        subtitle: Wireless Media Bridge
        tag: bridge
        url: https://bridge.diesel.net
        target: "_blank" # open in new tab

      - name: Arris SURFboard SB8200
        logo: assets/images/arris.png
        subtitle: Cable Modem
        tag: modem
        url: https://modem.diesel.net
        target: "_blank" # open in new tab

      - name: Synology DS920+
        logo: assets/images/dsm.png
        subtitle: Network Attached Storage
        tag: nas
        url: https://nas.kiwi-labs.net:5001
        target: "_blank" # open in new tab

      - name: CyberPower PR1500LCDN
        logo: assets/images/cyberpower.png
        subtitle: Uninterruptible Power Supply
        tag: ups
        url: https://ups.diesel.net
        target: "_blank" # open in new tab


  - name: Tools & Monitoring
    icon: fas fa-chart-area
    items:

      - name: Drone CI
        logo: assets/images/drone.png
        subtitle: Continuos Integration
        tag: drone
        url: https://drone.kiwi-labs.net
        target: "_blank" # open in new tab

      - name: Nexus Repository Manager
        logo: assets/images/nrm.png
        subtitle: Artifact repository
        tag: nexus
        url: https://nexus.diesel.net
        target: "_blank" # open in new tab

      - name: Grafana
        logo: assets/images/grafana.png
        subtitle: Query, Visualize, Monitor
        tag: grafana
        url: https://grafana.diesel.net
        target: "_blank" # open in new tab


      # - name: ntopng
      #   logo: assets/images/ntop.png
      #   subtitle: Traffic Analysis and Flow Collection
      #   tag: ntop
      #   url: https://pfsense.diesel.net:3000/
      #   target: "_blank" # open in new tab


  - name: Apps & Services
    icon: fas fa-cloud
    items:
      - name: Bitwarden
        logo: assets/images/bitwarden.png
        subtitle: Password Manager
        tag: bitwarden
        url: https://bitwarden.diesel.net
        target: "_blank" # open in new tab

      - name: Plex
        logo: assets/images/pms.png
        subtitle: Stream Movies and TV
        tag: plex
        url: https://app.plex.tv
        target: "_blank" # open in new tab

      - name: Handbrake
        logo: assets/images/handbrake.png
        subtitle: Video Trancoder
        tag: handbrake
        url: https://handbrake.diesel.net
        target: "_blank" # open in new tab

      - name: phpLDAPadmin
        logo: assets/images/phpldapadmin.png
        subtitle: Web-based LDAP client
        tag: ldap
        url: https://ldap.diesel.net
        target: "_blank" # open in new tab


  - name: Communities
    icon: fas fa-users
    items:

      - name: GitHub
        logo: assets/images/octocat.png
        subtitle: Source Code Management
        tag: github
        url: https://github.com
        target: "_blank" # open in new tab

      - name: Reddit
        logo: assets/images/reddit.png
        subtitle: The Front Page of the Internet
        tag: reddit
        url: https://reddit.com
        target: "_blank" # open in new tab   

  - name: Development
    icon: fas fa-code
    items:

      - name: kiwi-labs.net
        logo: assets/images/kiwi-labs.png
        subtitle: dev.diesel.net
        tag: kiwi-labs
        url: https://dev.diesel.net
        target: "_blank" # open in new tab

      - name: Traefik
        logo: assets/images/traefik.png
        subtitle: Reverse Proxy
        tag: traefik
        url: https://traefik.dev.diesel.net
        target: "_blank" # open in new tab  

  - name: Test
    icon: fas fa-vial
    items:

      - name: kiwi-labs.net
        logo: assets/images/kiwi-labs.png
        subtitle: test.diesel.net
        tag: kiwi-labs
        url: https://test.diesel.net
        target: "_blank" # open in new tab

      - name: Traefik
        logo: assets/images/traefik.png
        subtitle: Reverse Proxy
        tag: traefik
        url: https://traefik.test.diesel.net
        target: "_blank" # open in new tab  

  - name: Production
    icon: fas fa-industry
    items:

      - name: kiwi-labs.net (external)
        logo: assets/images/kiwi-labs.png
        subtitle: kiwi-labs.net
        tag: kiwi-labs
        url: https://kiwi-labs.net
        target: "_blank" # open in new tab

      - name: kiwi-labs.net (internal)
        logo: assets/images/kiwi-labs.png
        subtitle: prod.diesel.net
        tag: kiwi-labs
        url: https://prod.diesel.net
        target: "_blank" # open in new tab

      - name: Traefik
        logo: assets/images/traefik-2.png
        subtitle: Reverse Proxy
        tag: traefik
        url: https://traefik.prod.diesel.net
        target: "_blank" # open in new tab  

      - name: Traefik (drone)
        logo: assets/images/traefik.png
        subtitle: Reverse Proxy
        tag: traefik
        url: https://traefik.drone.diesel.net
        target: "_blank" # open in new tab  

      - name: Traefik (tools)
        logo: assets/images/traefik.png
        subtitle: Reverse Proxy
        tag: traefik
        url: https://traefik.tools.diesel.net
        target: "_blank" # open in new tab  

      - name: Traefik (quadro)
        logo: assets/images/traefik.png
        subtitle: Reverse Proxy
        tag: traefik
        url: https://traefik.quadro.diesel.net
        target: "_blank" # open in new tab 
